### ISSUE TITLE
Testing: Sign-In Test Accounts

### ISSUE THREAD

**Issue by laglau** [inforeliance/MedCheck#55]
The sign in page has content on test accounts, but these accounts are not setup

**Comment by irJasonBrannon** [comment]
The accounts are for the dev env and not promoted to prod.  We'll remove the copy, but keeping the issue open until committed.

**Comment by irJasonBrannon** [comment]
Replaced copy with new instructions, covering oAuth connections over Facebook, Twitter and Google.
