### ISSUE TITLE
Testing; Home Page graphic layout

### ISSUE THREAD

**Issue by laglau** [inforeliance/MedCheck#57]
Something is not aligned correctly on the home page. the main graphic is offset to the right of the navigation bar, so there is odd black space at the top to the right of the help link that shouldn't be there.  Need to extend the blue navigation background color so that the edge aligns with the right edge of the graphic, OR shift the graphic to the left so that the edge lines up that way. attempting to attach an image
![Uploading HomePage.JPG…]()

**Comment by irJasonBrannon** [comment]
For template and layout issues, please document your OS/Platform and Browser information.

ie.. OSX / Safar Version 8.0.6 (10600.6.3)  same thing for mobile.

**Comment by laglau** [comment]
Windows 7 Prof / IE v11

**Comment by irJasonBrannon** [comment]
Can you post a screenshot to http://tinypic.com/ and comment back with the link?

**Comment by laglau** [comment]
Let me know if this works: http://tinypic.com/r/52e79l/8

**Comment by irtimclark** [comment]
Fixed with checkin d894c28288daaedfd58b73b939f3afd7132d78ec
