### ISSUE TITLE
Testing: Search not checking entered allergens against ingredients

### ISSUE THREAD

**Issue by laglau** [inforeliance/MedCheck#61]
I ran a search on an over the counter med that is in my house using key words from the Active and Inactive ingredient list, and the search returned "no allergens"

**Comment by irtimclark** [comment]
Can you give a specific example?

**Comment by laglau** [comment]
Searched on Cold-Eeze. added: zincum and corn as allergens

**Comment by irtimclark** [comment]
It works. See: http://www.screencast.com/users/aquinas/folders/Jing/media/a2555156-7e65-4f22-a5d7-6cb1a162a1dd

Some of the cold-eeze products DIDN'T have corn, and for some reason, the active ingredient is "zinc" instead of zincum
