### ISSUE TITLE
Testing: Create Profile from Search not available

### ISSUE THREAD

**Issue by laglau** [inforeliance/MedCheck#63]
Are we building out the option to create a profile from entered search criteria or is that going to be part of the backlog?

**Comment by irJasonBrannon** [comment]
Topic that Tim and I are to discuss.  If an un-registered user, want's to generate a profile from a search, they must register for an account 1st, so the workflow would look like this:

- Un-registered user provides search criteria
- Searches, is offered to save search to profile
- Says "Yup" to that.
- Redirected to Register, creates account (Uname/pwd, or oAuth Google, Facebook...)
- Profile generated, name will come from the User's login account.

**Comment by irJasonBrannon** [comment]
Feature added.
